package com.hnnd.fastgo.vo;

import lombok.Data;

import java.io.Serializable;

/**
 * 商品类目VO对象
 * Created by 85073 on 2018/11/21.
 */
@Data
public class ItemCatVo implements Serializable {

    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_item_cat.parent_id
     *
     * @mbggenerated
     */
    private Long parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_item_cat.name
     *
     * @mbggenerated
     */
    private String itemCatName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_item_cat.type_id
     *
     * @mbggenerated
     */
    private String tempTypeId;
}
