package com.hnnd.fastgo.vo;

import lombok.Data;

/**
 * 商品类型模版
 * Created by 85073 on 2018/11/20.
 */
@Data
public class TemplateTypeVo {

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_type_template.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_type_template.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_type_template.spec_ids
     *
     * @mbggenerated
     */
    private String specIds;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_type_template.brand_ids
     *
     * @mbggenerated
     */
    private String brandIds;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_type_template.custom_attribute_items
     *
     * @mbggenerated
     */
    private String customAttributeItems;
}
