package com.hnnd.fastgo.dao;

import com.hnnd.fastgo.entity.DelFileLog;

import java.util.List;

public interface DelFileLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table del_file_log
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table del_file_log
     *
     * @mbggenerated
     */
    int insert(DelFileLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table del_file_log
     *
     * @mbggenerated
     */
    DelFileLog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table del_file_log
     *
     * @mbggenerated
     */
    List<DelFileLog> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table del_file_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(DelFileLog record);
}