package com.hnnd.fastgo.dao;


import com.hnnd.fastgo.entity.MsgLog;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface MsgLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_log
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String msgId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_log
     *
     * @mbggenerated
     */
    int insert(MsgLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_log
     *
     * @mbggenerated
     */
    MsgLog selectByPrimaryKey(String msgId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_log
     *
     * @mbggenerated
     */
    List<MsgLog> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MsgLog record);

    void updateMsgStatus(@Param("msgId")String msgId,@Param("msgStatus") Integer msgStatus);
}