package com.hnnd.fastgo.dao;

import com.hnnd.fastgo.entity.TbBrand;

import java.util.List;

public interface TbBrandMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_brand
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_brand
     *
     * @mbggenerated
     */
    int insert(TbBrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_brand
     *
     * @mbggenerated
     */
    TbBrand selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_brand
     *
     * @mbggenerated
     */
    List<TbBrand> selectAll();

    /**
     * 条件查询
     * @param tbBrand 查询条件
     * @return  List<TbBrand>
     */
    List<TbBrand> selectListByConditon(TbBrand tbBrand);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_brand
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TbBrand record);
}