package com.hnnd.fastgo.dao;

import com.hnnd.fastgo.entity.TbCities;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface TbCitiesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_cities
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_cities
     *
     * @mbggenerated
     */
    int insert(TbCities record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_cities
     *
     * @mbggenerated
     */
    TbCities selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_cities
     *
     * @mbggenerated
     */
    List<TbCities> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_cities
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TbCities record);
}