package com.hnnd.fastgo.dao;

import com.hnnd.fastgo.entity.TbItem;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TbItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_item
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_item
     *
     * @mbggenerated
     */
    int insert(TbItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_item
     *
     * @mbggenerated
     */
    TbItem selectByPrimaryKey(Long id);

    List<TbItem> selectByGoodsId(Long goodsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_item
     *
     * @mbggenerated
     */
    List<TbItem> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_item
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TbItem record);

    int updateByExampleSelective(TbItem tbItem);

    List<TbItem> selectSolrList();

    List<TbItem> selectSkuListBySpuId(List<Long> ids);

    List<TbItem> selectSkuListByStausWithSpuId(@Param("goodsId")Long goodId,@Param("status") String status);

    void batchUpdateTbItem(@Param(value = "list") List<TbItem> list);
}