package com.hnnd.fastgo.dao;

import com.hnnd.fastgo.entity.TbSeller;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

public interface TbSellerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_seller
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String sellerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_seller
     *
     * @mbggenerated
     */
    int insert(TbSeller record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_seller
     *
     * @mbggenerated
     */
    TbSeller selectByPrimaryKey(String sellerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_seller
     *
     * @mbggenerated
     */
    List<TbSeller> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_seller
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TbSeller record);
}