package com.hnnd.fastgo.dao;

import com.hnnd.fastgo.entity.TbSeller;
import org.apache.ibatis.annotations.Param;
import org.springframework.web.bind.annotation.PathVariable;

import java.util.List;

public interface TbSellerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_seller
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String sellerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_seller
     *
     * @mbggenerated
     */
    int insert(TbSeller record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_seller
     *
     * @mbggenerated
     */
    TbSeller selectByPrimaryKey(String sellerId);

    TbSeller loadUserByUserName(@Param("sellerId") String userName, @Param("status") String status);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_seller
     *
     * @mbggenerated
     */
    List<TbSeller> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_seller
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TbSeller record);


    int register(TbSeller tbSeller);

    /**
     * 校验用户名
     * @param sellerId 用户名``
     * @return
     */
    int checkSellerId(String sellerId);

    /**
     * 校验店铺名
     * @param nickName
     * @return
     */
    int checkNickName(String nickName);

    /**
     * 校验店铺名
     * @param linkmanMobile
     * @return
     */
    int checkLinkmanMobile(String linkmanMobile);

    /**
     * 根据条件查询列表
     * @param tbSeller 查询条件
     * @return
     */
    List<TbSeller> findListByCondition(TbSeller tbSeller);

    void updateAcctStatus(@Param("sellerId") String sellerId, @PathVariable("status") String status);
}