package com.hnnd.fastgo.entity;

import java.io.Serializable;
import java.util.Date;

public class MsgLog implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column msg_log.msg_id
     *
     * @mbggenerated
     */
    private String msgId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column msg_log.send_time
     *
     * @mbggenerated
     */
    private Date sendTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column msg_log.ack_time
     *
     * @mbggenerated
     */
    private Date ackTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column msg_log.msg_status
     *
     * @mbggenerated
     */
    private Integer msgStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column msg_log.max_retry_count
     *
     * @mbggenerated
     */
    private Integer maxRetryCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column msg_log.current_retry_count
     *
     * @mbggenerated
     */
    private Integer currentRetryCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column msg_log.msg_text
     *
     * @mbggenerated
     */
    private String msgText;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column msg_log.destination
     *
     * @mbggenerated
     */
    private String destination;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column msg_log.routing_key
     *
     * @mbggenerated
     */
    private String routingKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table msg_log
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column msg_log.msg_id
     *
     * @return the value of msg_log.msg_id
     *
     * @mbggenerated
     */
    public String getMsgId() {
        return msgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column msg_log.msg_id
     *
     * @param msgId the value for msg_log.msg_id
     *
     * @mbggenerated
     */
    public void setMsgId(String msgId) {
        this.msgId = msgId == null ? null : msgId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column msg_log.send_time
     *
     * @return the value of msg_log.send_time
     *
     * @mbggenerated
     */
    public Date getSendTime() {
        return sendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column msg_log.send_time
     *
     * @param sendTime the value for msg_log.send_time
     *
     * @mbggenerated
     */
    public void setSendTime(Date sendTime) {
        this.sendTime = sendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column msg_log.ack_time
     *
     * @return the value of msg_log.ack_time
     *
     * @mbggenerated
     */
    public Date getAckTime() {
        return ackTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column msg_log.ack_time
     *
     * @param ackTime the value for msg_log.ack_time
     *
     * @mbggenerated
     */
    public void setAckTime(Date ackTime) {
        this.ackTime = ackTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column msg_log.msg_status
     *
     * @return the value of msg_log.msg_status
     *
     * @mbggenerated
     */
    public Integer getMsgStatus() {
        return msgStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column msg_log.msg_status
     *
     * @param msgStatus the value for msg_log.msg_status
     *
     * @mbggenerated
     */
    public void setMsgStatus(Integer msgStatus) {
        this.msgStatus = msgStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column msg_log.max_retry_count
     *
     * @return the value of msg_log.max_retry_count
     *
     * @mbggenerated
     */
    public Integer getMaxRetryCount() {
        return maxRetryCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column msg_log.max_retry_count
     *
     * @param maxRetryCount the value for msg_log.max_retry_count
     *
     * @mbggenerated
     */
    public void setMaxRetryCount(Integer maxRetryCount) {
        this.maxRetryCount = maxRetryCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column msg_log.current_retry_count
     *
     * @return the value of msg_log.current_retry_count
     *
     * @mbggenerated
     */
    public Integer getCurrentRetryCount() {
        return currentRetryCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column msg_log.current_retry_count
     *
     * @param currentRetryCount the value for msg_log.current_retry_count
     *
     * @mbggenerated
     */
    public void setCurrentRetryCount(Integer currentRetryCount) {
        this.currentRetryCount = currentRetryCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column msg_log.msg_text
     *
     * @return the value of msg_log.msg_text
     *
     * @mbggenerated
     */
    public String getMsgText() {
        return msgText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column msg_log.msg_text
     *
     * @param msgText the value for msg_log.msg_text
     *
     * @mbggenerated
     */
    public void setMsgText(String msgText) {
        this.msgText = msgText == null ? null : msgText.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column msg_log.destination
     *
     * @return the value of msg_log.destination
     *
     * @mbggenerated
     */
    public String getDestination() {
        return destination;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column msg_log.destination
     *
     * @param destination the value for msg_log.destination
     *
     * @mbggenerated
     */
    public void setDestination(String destination) {
        this.destination = destination == null ? null : destination.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column msg_log.routing_key
     *
     * @return the value of msg_log.routing_key
     *
     * @mbggenerated
     */
    public String getRoutingKey() {
        return routingKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column msg_log.routing_key
     *
     * @param routingKey the value for msg_log.routing_key
     *
     * @mbggenerated
     */
    public void setRoutingKey(String routingKey) {
        this.routingKey = routingKey == null ? null : routingKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_log
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", msgId=").append(msgId);
        sb.append(", sendTime=").append(sendTime);
        sb.append(", ackTime=").append(ackTime);
        sb.append(", msgStatus=").append(msgStatus);
        sb.append(", maxRetryCount=").append(maxRetryCount);
        sb.append(", currentRetryCount=").append(currentRetryCount);
        sb.append(", msgText=").append(msgText);
        sb.append(", destination=").append(destination);
        sb.append(", routingKey=").append(routingKey);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}